### ISSUE TITLE
Segfault when removing color scheme

### ISSUE THREAD

**Issue by mpetroff** [linuxmint/xed#25]
With xed 1.0.6 on Linux Mint 18, I'm able to consistently get a segfault when removing a color scheme.

Steps to reproduce:
1. Open Preferences dialog and navigate to Fonts & Colors tab
2. Add a new color scheme
3. Select a color scheme different than the one just added
4. Select the color scheme that was just added
5. Click remove

Here's a backtrace:

```
Thread 1 "xed" received signal SIGSEGV, Segmentation fault.
0x00007ffff71049db in gtk_tree_model_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
(gdb) bt
#0  0x00007ffff71049db in gtk_tree_model_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#1  0x00007ffff7104cf9 in gtk_tree_model_get () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#2  0x000000000046e021 in style_scheme_changed (treeview=<optimized out>, dlg=0xee65d0)
    at xed-preferences-dialog.c:650
#3  0x00007ffff5b9f1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff5bb99a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff5bba08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7124070 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff7127944 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff5b9efa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff5bb0fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff5bb9d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff5bba08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6ff9eb5 in gtk_list_store_remove () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff6ffa62f in gtk_list_store_clear () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x000000000046db51 in populate_color_scheme_list (dlg=dlg@entry=0xee65d0, def_id=0xffaf40 "oblivion")
    at xed-preferences-dialog.c:706
#15 0x000000000046deb2 in uninstall_scheme_clicked (button=<optimized out>, dlg=0xee65d0)
    at xed-preferences-dialog.c:923
#16 0x00007ffff5b9f1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff5bb99a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff5bba08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6f0c6ad in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff6f0c715 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff5b9f1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff5bb99a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff5bba08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff6f0a7a0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007fffeffc2e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#26 0x00007fffeffc28ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#27 0x00007ffff5b9fcf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff5b9f1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff5bb99a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff5bba08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff6fb8891 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff5ba1dbe in g_cclosure_marshal_VOID__BOXEDv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff5b9f1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff5bb99a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff5bba08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff6fb5bee in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff6fb722b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff6fb9de5 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff6f89beb in gtk_event_controller_handle_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff713ac1b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff6fff09a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff5b9f1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff5bb94b8 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff5bba08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff713cc5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#46 0x00007ffff6ffc3be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007ffff6ffe1bc in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff6b6bca2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#49 0x00007ffff58c81a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007ffff58c8400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#51 0x00007ffff58c8722 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#52 0x00007ffff6ffd395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#53 0x0000000000427290 in main (argc=1, argv=0x7fffffffdf68) at xed.c:645
```

**Comment by JosephMcc** [comment]
I can reproduce this on the latest git master.
