### ISSUE TITLE
[Bug] Closing one xed window kills all other open xed windows.

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/xed#250]
```
 * Xed version: xed - Version 1.8.3
 * Distribution: Fedora 29 (issue also present on 28)
```

**Issue**
Often I have multiple instances of xed open each with several tabs, sometimes closing one instance leads to this crash, all other instances are also killed by the crash.
It's happened several times.

```
$ coredumpctl list |grep xed
Tue 2018-07-24 17:48:30 BST   29956  1000  1000   7 missing   /usr/bin/xed
Tue 2018-07-24 20:51:04 BST    9376  1000  1000   7 missing   /usr/bin/xed
Tue 2018-07-24 21:00:09 BST   21872  1000  1000   7 missing   /usr/bin/xed
Sat 2018-08-11 12:27:06 BST   32579  1000  1000   7 missing   /usr/bin/xed
Mon 2018-08-13 14:57:56 BST    2484  1000  1000   7 missing   /usr/bin/xed
Sat 2018-08-18 11:09:31 BST    7980  1000  1000   7 missing   /usr/bin/xed
Sat 2018-08-25 18:43:27 BST   13311     0     0   7 missing   /usr/bin/xed
Mon 2018-08-27 17:06:17 BST    7725  1000  1000   7 missing   /usr/bin/xed
Mon 2018-08-27 18:32:39 BST    8382  1000  1000   7 missing   /usr/bin/xed
Fri 2018-08-31 14:06:04 BST   21115  1000  1000   7 missing   /usr/bin/xed
Sat 2018-09-01 15:01:29 BST   30921  1000  1000   7 missing   /usr/bin/xed
Sat 2018-09-01 18:29:39 BST    3226  1000  1000   7 missing   /usr/bin/xed
Mon 2018-09-03 14:25:40 BST    4296  1000  1000   7 present   /usr/bin/xed
Wed 2018-09-05 15:07:56 BST   19055  1000  1000   7 present   /usr/bin/xed
Wed 2018-09-05 18:01:37 BST   22400  1000  1000   7 present   /usr/bin/xed
```

**Steps to reproduce**
Happens in normal work flow when closing a xed window.

**Expected behaviour**
It would be mega cool if this didn't occur :-)

**Other information**

~/.xsession-errors has these warnings.

```
(xed:19448): Gtk-WARNING **: 12:58:02.243: gtk_widget_size_allocate(): attempt to underallocate toplevel GtkWindow 0x564f2e66cf90. Allocation is 24x24, but minimum required size is 250x180.

(xed:19448): Gtk-WARNING **: 12:58:02.243: gtk_widget_size_allocate(): attempt to underallocate GtkWindow's child GtkWindow 0x564f2e66ccf0. Allocation is 24x24, but minimum required size is 250x180.

** (xed:19448): WARNING **: 15:07:57.374: Set document metadata failed: Setting attribute metadata::xed-position not supported
```

back and stack traces.

```
$ coredumpctl --no-pager gdb 22400
           PID: 22400 (xed)
           UID: 1000 (leigh)
           GID: 1000 (leigh)
        Signal: 7 (BUS)
     Timestamp: Wed 2018-09-05 18:01:36 BST (12min ago)
  Command Line: xed /home/leigh/Desktop/bluez-tools/bluez-tools.spec
    Executable: /usr/bin/xed
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (leigh)
       Boot ID: 58c0e685ba4a4d47a96269fb9bff40a2
    Machine ID: c36eea9071e643fa98e7d221be4956e1
      Hostname: localhost.localdomain
       Storage: /var/lib/systemd/coredump/core.xed.1000.58c0e685ba4a4d47a96269fb9bff40a2.22400.1536166896000000.lz4
       Message: Process 22400 (xed) of user 1000 dumped core.
                
                Stack trace of thread 22400:
                #0  0x00007fa32d251f00 gtk_action_group_get_action (libgtk-3.so.0)
                #1  0x00007fa32dc274a0 n/a (libxed.so)
                #2  0x00007fa32d594a9b n/a (libgtk-3.so.0)
                #3  0x00007fa32cb00e0d g_closure_invoke (libgobject-2.0.so.0)
                #4  0x00007fa32cb14f13 n/a (libgobject-2.0.so.0)
                #5  0x00007fa32cb1e32a g_signal_emit_valist (libgobject-2.0.so.0)
                #6  0x00007fa32cb1ee04 g_signal_emit_by_name (libgobject-2.0.so.0)
                #7  0x00007fa32d49cfe3 n/a (libgtk-3.so.0)
                #8  0x00007fa32d4a126d n/a (libgtk-3.so.0)
                #9  0x00007fa32d5c1d48 n/a (libgtk-3.so.0)
                #10 0x00007fa32cb01066 n/a (libgobject-2.0.so.0)
                #11 0x00007fa32cb1dda4 g_signal_emit_valist (libgobject-2.0.so.0)
                #12 0x00007fa32cb1e923 g_signal_emit (libgobject-2.0.so.0)
                #13 0x00007fa32d5679b4 n/a (libgtk-3.so.0)
                #14 0x00007fa32d40a06a gtk_main_do_event (libgtk-3.so.0)
                #15 0x00007fa32d0bcfd9 n/a (libgdk-3.so.0)
                #16 0x00007fa32d0f1c06 n/a (libgdk-3.so.0)
                #17 0x00007fa32ca1e2ad g_main_context_dispatch (libglib-2.0.so.0)
                #18 0x00007fa32ca1e678 n/a (libglib-2.0.so.0)
                #19 0x00007fa32ca1e710 g_main_context_iteration (libglib-2.0.so.0)
                #20 0x00007fa32ce9b0b5 g_application_run (libgio-2.0.so.0)
                #21 0x000055d066ce1273 main (xed)
                #22 0x00007fa32c67c413 __libc_start_main (libc.so.6)
                #23 0x000055d066ce12be _start (xed)
                
                Stack trace of thread 22402:
                #0  0x00007fa32c74a301 __poll (libc.so.6)
                #1  0x00007fa32ca1e5e6 n/a (libglib-2.0.so.0)
                #2  0x00007fa32ca1e710 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fa32ca1e761 n/a (libglib-2.0.so.0)
                #4  0x00007fa32ca476ea n/a (libglib-2.0.so.0)
                #5  0x00007fa32c82858e start_thread (libpthread.so.0)
                #6  0x00007fa32c755513 __clone (libc.so.6)
                
                Stack trace of thread 22404:
                #0  0x00007fa32c74a301 __poll (libc.so.6)
                #1  0x00007fa32ca1e5e6 n/a (libglib-2.0.so.0)
                #2  0x00007fa32ca1e710 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fa31dba160d n/a (libdconfsettings.so)
                #4  0x00007fa32ca476ea n/a (libglib-2.0.so.0)
                #5  0x00007fa32c82858e start_thread (libpthread.so.0)
                #6  0x00007fa32c755513 __clone (libc.so.6)
                
                Stack trace of thread 22403:
                #0  0x00007fa32c74a301 __poll (libc.so.6)
                #1  0x00007fa32ca1e5e6 n/a (libglib-2.0.so.0)
                #2  0x00007fa32ca1e9a2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fa32cec990a n/a (libgio-2.0.so.0)
                #4  0x00007fa32ca476ea n/a (libglib-2.0.so.0)
                #5  0x00007fa32c82858e start_thread (libpthread.so.0)
                #6  0x00007fa32c755513 __clone (libc.so.6)
                
                Stack trace of thread 32237:
                #0  0x00007fa32c74fd6d syscall (libc.so.6)
                #1  0x00007fa32ca6628e g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fa32c9f01f1 n/a (libglib-2.0.so.0)
                #3  0x00007fa32ca48232 n/a (libglib-2.0.so.0)
                #4  0x00007fa32ca476ea n/a (libglib-2.0.so.0)
                #5  0x00007fa32c82858e start_thread (libpthread.so.0)
                #6  0x00007fa32c755513 __clone (libc.so.6)

GNU gdb (GDB) Fedora 8.1.90.20180727-45.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/xed...Reading symbols from /usr/lib/debug/usr/bin/xed-1.8.3-1.fc29.x86_64.debug...done.
done.
[New LWP 22400]
[New LWP 22402]
[New LWP 22404]
[New LWP 22403]
[New LWP 32237]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Missing separate debuginfo for /lib64/libmount.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/f8/327d6d1741a9ca39a96f2bc253d74d6f05034e.debug

Core was generated by `xed /home/leigh/Desktop/bluez-tools/bluez-tools.spec'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00007fa32d251f00 in gtk_action_group_get_action (action_group=0x55d068c2f680, action_name=0x7fa32dc3b2e6 "EditPaste") at deprecated/gtkactiongroup.c:885
885	  g_return_val_if_fail (GTK_IS_ACTION_GROUP (action_group), NULL);
[Current thread is 1 (Thread 0x7fa32d063a80 (LWP 22400))]
(gdb) bt full
#0  0x00007fa32d251f00 in gtk_action_group_get_action (action_group=0x55d068c2f680, action_name=0x7fa32dc3b2e6 "EditPaste") at deprecated/gtkactiongroup.c:885
        __inst = 0x55d068c2f680
        __r = <optimized out>
        _g_boolean_var_ = <optimized out>
        __func__ = "gtk_action_group_get_action"
#1  0x00007fa32dc274a0 in received_clipboard_contents (clipboard=<optimized out>, selection_data=<optimized out>, window=0x55d068d8de10 [XedWindow]) at xed-window.c:520
        sensitive = 0
        action = <optimized out>
#2  0x00007fa32d594a9b in selection_received (widget=0x55d068fb5f90 [GtkInvisible], selection_data=0x7ffd6fb4a3c0, time=<optimized out>) at gtkclipboard.c:960
        request_info = 0x55d068b918d0
#6  0x00007fa32cb1ee04 in <emit signal 0x7fa32d62fe04 "selection-received" on instance 0x55d068fb5f90 [GtkInvisible]> (instance=0x55d068fb5f90, detailed_signal=detailed_signal@entry=0x7fa32d62fe04 "selection-received") at gsignal.c:3487
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffd6fb4a3c0, reg_save_area = 0x7ffd6fb4a2d0}}
        detail = 0
        signal_id = 101
        itype = 0x55d069836580 [GtkInvisible/GtkWidget/GInitiallyUnowned]
        __func__ = "g_signal_emit_by_name"
    #3  0x00007fa32cb00e0d in g_closure_invoke (closure=0x55d069837070, return_value=0x0, n_param_values=3, param_values=0x7ffd6fb4a050, invocation_hint=0x7ffd6fb49fd0) at gclosure.c:810
                marshal = 0x7fa32d5c6400 <_gtk_marshal_VOID__BOXED_UINT>
                marshal_data = 0x0
                in_marshal = 0
                real_closure = 0x55d069837050
                __func__ = "g_closure_invoke"
    #4  0x00007fa32cb14f13 in signal_emit_unlocked_R (node=node@entry=0x55d0688b21b0, detail=detail@entry=0, instance=instance@entry=0x55d068fb5f90, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffd6fb4a050) at gsignal.c:3635
                tmp = <optimized out>
                handler = 0x55d069370d80
                accumulator = 0x0
                emission = {next = 0x7ffd6fb4a600, instance = 0x55d068fb5f90, ihint = {signal_id = 101, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 0x4 [void]}
                class_closure = 0x55d0688b61b0
                hlist = <optimized out>
                handler_list = 0x55d069370d80
                return_accu = 0x0
                accu = 
                      {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 101
                max_sequential_handler_number = 56156
                return_value_altered = 0
    #5  0x00007fa32cb1e32a in g_signal_emit_valist (instance=instance@entry=0x55d068fb5f90, signal_id=signal_id@entry=101, detail=detail@entry=0, var_args=var_args@entry=0x7ffd6fb4a288) at gsignal.c:3391
                instance_and_params = 0x7ffd6fb4a050
                signal_return_type = <optimized out>
                param_values = 0x7ffd6fb4a068
                node = <optimized out>
                i = <optimized out>
                n_params = <optimized out>
                __func__ = "g_signal_emit_valist"
#7  0x00007fa32d49cfe3 in gtk_selection_retrieval_report (info=info@entry=0x55d068b30c30, type=<optimized out>, format=<optimized out>, buffer=<optimized out>, length=length@entry=96, time=92409210) at gtkselection.c:3049
        data = {selection = 0x45, target = 0xa0, type = 0x4, format = 32, data = 0x55d0692d05f0 "\244", length = 96, display = 0x55d0688cd000 [GdkX11Display]}
#8  0x00007fa32d4a126d in _gtk_selection_notify (widget=<optimized out>, event=0x55d0698f62a0) at gtkselection.c:2853
        tmp_list = 0x55d06c8e9200 = {0x55d068a49460}
        info = 0x55d068b30c30
        window = 0x55d06934f4c0 [GdkX11Window]
        buffer = 0x55d0692d05f0 "\244"
        length = 96
        type = 0x4
        format = 32
#9  0x00007fa32d5c1d48 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x55d0688b5f90, return_value=0x7ffd6fb4a630, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55d0688b5fc0) at gtkmarshalers.c:129
        cc = 0x55d0688b5f90
        data1 = 0x55d068fb5f90
        data2 = <optimized out>
        callback = <optimized out>
        v_return = <optimized out>
        arg0 = 0x55d0698f62a0
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffd6fb4a7e0, reg_save_area = 0x7ffd6fb4a720}}
        __func__ = "_gtk_marshal_BOOLEAN__BOXEDv"
#10 0x00007fa32cb01066 in _g_closure_invoke_va (closure=0x55d0688b5f90, return_value=0x7ffd6fb4a630, instance=0x55d068fb5f90, args=0x7ffd6fb4a700, n_params=1, param_types=0x55d0688b5fc0) at gclosure.c:873
        marshal = 0x7fa32caff240 <g_type_class_meta_marshalv>
        marshal_data = 0x210
        in_marshal = 0
        real_closure = 0x55d0688b5f70
        __func__ = "_g_closure_invoke_va"
#11 0x00007fa32cb1dda4 in g_signal_emit_valist (instance=0x55d068fb5f90, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffd6fb4a700) at gsignal.c:3300
        return_accu = 0x7ffd6fb4a630
        accu = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x55d0688b6050
        emission = {next = 0x0, instance = 0x55d068fb5f90, ihint = {signal_id = 100, detail = 0, run_type = G_SIGNAL_RUN_LAST}, state = EMISSION_RUN, chain_type = 0x55d069836580 [GtkInvisible/GtkWidget/GInitiallyUnowned]}
        signal_id = 100
        instance_type = 0x55d069836580 [GtkInvisible/GtkWidget/GInitiallyUnowned]
        emission_return = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x14 [gboolean]
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = 0x55d0688b5fe0
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#12 0x00007fa32cb1e923 in g_signal_emit (instance=instance@entry=0x55d068fb5f90, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffd6fb4a7e0, reg_save_area = 0x7ffd6fb4a720}}
#13 0x00007fa32d5679b4 in gtk_widget_event_internal (widget=widget@entry=0x55d068fb5f90 [GtkInvisible], event=event@entry=0x55d0698f62a0) at gtkwidget.c:7744
        signal_num = <optimized out>
        return_val = <optimized out>
        handled = 0
        __func__ = "gtk_widget_event_internal"
#14 0x00007fa32d569d5e in gtk_widget_event (widget=widget@entry=0x55d068fb5f90 [GtkInvisible], event=event@entry=0x55d0698f62a0) at gtkwidget.c:7314
        __func__ = "gtk_widget_event"
#15 0x00007fa32d40a06a in gtk_main_do_event (event=<optimized out>) at gtkmain.c:1855
        grab_widget = 0x55d068fb5f90 [GtkInvisible]
        window_group = 0x7fa314001ba0 [GtkWindowGroup]
        rewritten_event = <optimized out>
        device = 0x0
        tmp_list = <optimized out>
        event_widget = 0x55d068fb5f90 [GtkInvisible]
        topmost_widget = <optimized out>
        event = 0x55d0698f62a0
        __func__ = "gtk_main_do_event"
        __func__ = "gtk_main_do_event"
#16 0x00007fa32d0bcfd9 in _gdk_event_emit (event=event@entry=0x55d0698f62a0) at gdkevents.c:73
#17 0x00007fa32d0f1c06 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at gdkeventsource.c:367
        display = <optimized out>
        event = 0x55d0698f62a0
#18 0x00007fa32ca1e2ad in g_main_dispatch (context=0x55d06889b380) at gmain.c:3182
        dispatch = 0x7fa32d0f1be0 <gdk_event_source_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x55d0688e5490
        current = 0x55d0688a85c0
        i = 0
        __func__ = "g_main_dispatch"
#19 0x00007fa32ca1e2ad in g_main_context_dispatch (context=context@entry=0x55d06889b380) at gmain.c:3847
#20 0x00007fa32ca1e678 in g_main_context_iterate (context=context@entry=0x55d06889b380, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3920
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x55d068cdbf20
#21 0x00007fa32ca1e710 in g_main_context_iteration (context=context@entry=0x55d06889b380, may_block=may_block@entry=1) at gmain.c:3981
        retval = <optimized out>
#22 0x00007fa32ce9b0b5 in g_application_run (application=0x55d068898180 [XedApp], argc=<optimized out>, argv=0x7ffd6fb4ab38) at gapplication.c:2470
        arguments = 0x55d068897cc0
        status = 0
        context = 0x55d06889b380
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#23 0x000055d066ce1273 in main (argc=2, argv=0x7ffd6fb4ab38) at xed.c:65
        app = 0x55d068898180 [XedApp]
        status = <optimized out>
        dir = <optimized out>
(gdb) 
```

[crash.txt](https://github.com/linuxmint/xed/files/2353913/crash.txt)

**Comment by icarter09** [comment]
@leigh123linux any update on this issue?

**Comment by leigh123linux** [comment]
It's was fixed a while back and forgot to close.
