### ISSUE TITLE
xed crashes if you open an unmounted network share

### ISSUE THREAD

**Issue by Fischblick** [linuxmint/xed#286]
```
 * Xed version: 2.0.2
 * Distribution: Linux Mint 19.1 Cinnamon 4.0.10  Kernel 4.18.0-17-generic
```

**Issue**
xed crashes if you open an unmounted network share from your xed file browser bookmarks

**Steps to reproduce**
* Open file browser Nemo (4.0.6)
* Create a bookmark in Nemo
   * Use address bar smb://mydocumentfolder and press enter
   * Add that share to your nemo bookmarks
* Unmount the share or restart your pc
* Open xed and navigate to your unmounted share via your Bookmarks, use the file browser on the left
* xed crashes

**Expected behaviour**
xed mount the share on the fly and you can see your content. It is a little bit annoying if you have to open nemo first and mount it or writing a script to mount it during start up. 

**Other information**

**Comment by icarter09** [comment]
@Fischblick are you still experiencing this issue?

**Comment by Fischblick** [comment]
Hi @icarter09 ,
Yes same behavior.
Best regards Simon

**Comment by leigh123linux** [comment]
```
(gdb) bt full 
#0  0x00007f54317c4cf4 in xed_file_browser_store_set_root_and_virtual_root (model=0x55c856ba3a00 [XedFileBrowserStore], root=0x55c856bd8320, virtual_root=0x55c856bd8320) at ../plugins/filebrowser/xed-file-browser-store.c:3227
        node = <optimized out>
        equal = <optimized out>
        __func__ = "xed_file_browser_store_set_root_and_virtual_root"
#1  0x00007f54317cbd70 in xed_file_browser_widget_set_root_and_virtual_root (obj=0x55c856b8a3c0 [XedFileBrowserWidget], root=<optimized out>, virtual_root=<optimized out>) at ../plugins/filebrowser/xed-file-browser-widget.c:1738
        result = <optimized out>
#2  0x00007f54317cbf80 in bookmark_open (obj=0x55c856b8a3c0 [XedFileBrowserWidget], model=0x55c856ba3a80, iter=<optimized out>) at ../plugins/filebrowser/xed-file-browser-widget.c:2294
        location = 0x55c856bd8320
        flags = 3072
#6  0x00007f5442da89d3 in <emit signal ??? on instance 0x55c856bfaab0 [XedFileBrowserView]> (instance=instance@entry=0x55c856bfaab0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3453
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fff1adc9130, reg_save_area = 0x7fff1adc9070}}
    #3  0x00007f5442d8b742 in g_closure_invoke (closure=0x55c856c0ad60, return_value=0x0, n_param_values=2, param_values=0x7fff1adc8e70, invocation_hint=0x7fff1adc8df0) at ../gobject/gclosure.c:810
                marshal = 0x7f5442d8ea60 <g_cclosure_marshal_VOID__BOXED>
                marshal_data = 0x0
                in_marshal = 0
                real_closure = 0x55c856c0ad40
                __FUNCTION__ = "g_closure_invoke"
    #4  0x00007f5442d9f604 in signal_emit_unlocked_R
    (node=node@entry=0x7f5424007590, detail=detail@entry=0, instance=instance@entry=0x55c856bfaab0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fff1adc8e70) at ../gobject/gsignal.c:3641
                tmp = <optimized out>
                handler = 0x55c856c0a200
                accumulator = 0x0
                emission = {next = 0x7fff1adc9380, instance = 0x55c856bfaab0, ihint = {signal_id = 465, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 0x4 [void]}
                class_closure = 0x55c856bf6be0
                hlist = <optimized out>
                handler_list = 0x55c856c0a200
                return_accu = 0x0
                accu = 
                      {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 465
                max_sequential_handler_number = 5776
                return_value_altered = 0
    #5  0x00007f5442da83ae in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fff1adc9050) at ../gobject/gsignal.c:3397
                instance_and_params = 0x7fff1adc8e70
                signal_return_type = <optimized out>
                param_values = 0x7fff1adc8e88
                node = <optimized out>
                i = <optimized out>
                n_params = <optimized out>
                __FUNCTION__ = "g_signal_emit_valist"
#7  0x00007f54317c6f6d in activate_selected_bookmark (view=0x55c856bfaab0 [XedFileBrowserView]) at ../plugins/filebrowser/xed-file-browser-view.c:294
        tree_view = <optimized out>
        selection = <optimized out>
        iter = {stamp = 1901341855, user_data = 0x7f5424028c90, user_data2 = 0x0, user_data3 = 0x0}
#8  activate_selected_items (view=view@entry=0x55c856bfaab0 [XedFileBrowserView]) at ../plugins/filebrowser/xed-file-browser-view.c:307
#9  0x00007f54317c7ca8 in button_press_event (widget=widget@entry=0x55c856bfaab0 [XedFileBrowserView], event=0x55c856dc5470) at ../plugins/filebrowser/xed-file-browser-view.c:476
        double_click_time = 400
        click_count = 2
        last_click_time = 161552467
        view = 0x55c856bfaab0 [XedFileBrowserView]
        tree_view = <optimized out>
        selection = 0x7f5428003b50 [GtkTreeSelection]
        path = 0x55c8568e2f60
        expander_size = 16
        horizontal_separator = 4
        on_expander = <optimized out>
        call_parent = 1
        selected = <optimized out>
        widget_parent = 0x55c856b06de0
#14 0x00007f5442da89d3 in <emit signal ??? on instance 0x55c856bfaab0 [XedFileBrowserView]> (instance=instance@entry=0x55c856bfaab0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3453
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fff1adc96d0, reg_save_area = 0x7fff1adc9610}}
    #10 0x00007f544274fcab in _gtk_marshal_BOOLEAN__BOXED (closure=0x55c85635f160, return_value=0x7fff1adc93b0, n_param_values=<optimized out>, param_values=0x7fff1adc9410, invocation_hint=<optimized out>, marshal_data=<optimized out>) at gtkmarshalers.c:83
                cc = 0x55c85635f160
                data1 = 0x55c856bfaab0
                data2 = <optimized out>
                callback = 0x7f54317c7970 <button_press_event>
                v_return = <optimized out>
                __func__ = "_gtk_marshal_BOOLEAN__BOXED"
    #11 0x00007f5442d8b742 in g_closure_invoke (closure=0x55c85635f160, return_value=0x7fff1adc93b0, n_param_values=2, param_values=0x7fff1adc9410, invocation_hint=0x7fff1adc9390) at ../gobject/gclosure.c:810
                marshal = 0x7f5442d89c50 <g_type_class_meta_marshal>
                marshal_data = 0x180
                in_marshal = 0
                real_closure = 0x55c85635f140
                __FUNCTION__ = "g_closure_invoke"
    #12 0x00007f5442d9ed84 in signal_emit_unlocked_R (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x55c856bfaab0, emission_return=emission_return@entry=0x7fff1adc9540, instance_and_params=instance_and_params@entry=0x7fff1adc9410) at ../gobject/gsignal.c:3679
                accumulator = 0x55c85635f220
                emission = {next = 0x0, instance = 0x55c856bfaab0, ihint = {signal_id = 84, detail = 0, run_type = G_SIGNAL_RUN_LAST}, state = EMISSION_RUN, chain_type = 0x55c8565cc2d0 [XedFileBrowserView/GtkTreeView/GtkContainer/GtkWidget/GInitiallyUnowned]}
                class_closure = 0x55c85635f160
                hlist = <optimized out>
                handler_list = <optimized out>
                return_accu = 0x7fff1adc93b0
                accu = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 84
                max_sequential_handler_number = 5776
                return_value_altered = 1
    #13 0x00007f5442da7a21 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fff1adc95f0) at ../gobject/gsignal.c:3407
                return_value = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                error = 0x0
                rtype = 0x14 [gboolean]
                static_scope = 0
                instance_and_params = 0x7fff1adc9410
                signal_return_type = <optimized out>
                param_values = 0x7fff1adc9428
                node = <optimized out>
                i = <optimized out>
                n_params = <optimized out>
                __FUNCTION__ = "g_signal_emit_valist"
#15 0x00007f54426fa823 in gtk_widget_event_internal (event=0x55c856dc5470, widget=0x55c856bfaab0 [XedFileBrowserView]) at gtkwidget.c:7808
        signal_num = <optimized out>
        return_val = <optimized out>
        handled = 0
        __func__ = "gtk_widget_event_internal"
        __func__ = "gtk_widget_event_internal"
#16 gtk_widget_event_internal (widget=0x55c856bfaab0 [XedFileBrowserView], event=0x55c856dc5470) at gtkwidget.c:7677
        __func__ = "gtk_widget_event_internal"
#17 0x00007f54425b6168 in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0x55c856bfaab0 [XedFileBrowserView]) at gtkmain.c:2584
        tmp = <optimized out>
        handled_event = <optimized out>
        handled_event = 0
#18 propagate_event (widget=<optimized out>, event=0x55c856dc5470, captured=<optimized out>, topmost=0x0) at gtkmain.c:2687
        handled_event = 0
#19 0x00007f54425b837b in gtk_main_do_event (event=0x55c856dc5470) at gtkmain.c:1917
        grab_widget = 0x55c856bfaab0 [XedFileBrowserView]
        window_group = 0x55c8564e5010 [GtkWindowGroup]
        rewritten_event = <optimized out>
        device = <optimized out>
        tmp_list = <optimized out>
        event_widget = 0x55c856bfaab0 [XedFileBrowserView]
        topmost_widget = <optimized out>
        __func__ = "gtk_main_do_event"
        __func__ = "gtk_main_do_event"
#20 gtk_main_do_event (event=<optimized out>) at gtkmain.c:1687
        __func__ = "gtk_main_do_event"
#21 0x00007f544229cf79 in _gdk_event_emit (event=event@entry=0x55c856dc5470) at gdkevents.c:73
#22 0x00007f54422d0086 in gdk_event_source_dispatch (source=source@entry=0x55c85634b420, callback=<optimized out>, user_data=<optimized out>) at gdkeventsource.c:367
        display = <optimized out>
        event = 0x55c856dc5470
#23 0x00007f5442ad14a0 in g_main_dispatch (context=0x55c8563632c0) at ../glib/gmain.c:3179
        dispatch = <optimized out>
        prev_source = 0x0
        was_in_call = <optimized out>
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x55c85634b420
        current = 0x55c856378aa0
        i = 0
        __FUNCTION__ = "g_main_dispatch"
#24 g_main_context_dispatch (context=context@entry=0x55c8563632c0) at ../glib/gmain.c:3844
#25 0x00007f5442ad1830 in g_main_context_iterate (context=context@entry=0x55c8563632c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3917
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x55c8564b6ae0
#26 0x00007f5442ad18d3 in g_main_context_iteration (context=context@entry=0x55c8563632c0, may_block=may_block@entry=1) at ../glib/gmain.c:3978
        retval = <optimized out>
#27 0x00007f5442eb8d35 in g_application_run (application=0x55c85635c170 [XedApp], argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2559
        arguments = 0x55c85635b720
        status = 0
        context = 0x55c8563632c0
        acquired_context = 1
        __FUNCTION__ = "g_application_run"
#28 0x000055c8550b2276 in main (argc=1, argv=0x7fff1adc9a68) at ../xed/xed.c:62
        app = 0x55c85635c170 [XedApp]
        status = <optimized out>
        dir = <optimized out>
```

**Comment by Fischblick** [comment]
It is also crashing with Linux Mint  19.3 (Tricia) and xed version 2.4.2
